### ISSUE TITLE
Missing Emojis

### ISSUE THREAD

**Issue by gollum23** [syuchan1005/GitPrefix#12]
Hi, Just now i update the plugin to the last versión 1.5.4 but i can't see the emojis in commit window and gitprefix file, i attach error log.
```
2018-08-02 22:08:16,946 [  85773]  ERROR - enapi.editor.impl.DocumentImpl - com.intellij.openapi.editor.ex.util.LexerEditorHighlighter(com.github.syuchan1005.gitprefix.psi.PrefixResourceLexerAdapter): Error updating  after DocumentEventImpl[myOffset=304, myOldLength=1, myNewLength=0, myOldString='p', myNewString='']. 
com.intellij.openapi.editor.ex.util.LexerEditorHighlighter$InvalidStateException: com.intellij.openapi.editor.ex.util.LexerEditorHighlighter(com.github.syuchan1005.gitprefix.psi.PrefixResourceLexerAdapter): Error updating  after DocumentEventImpl[myOffset=304, myOldLength=1, myNewLength=0, myOldString='p', myNewString=''].
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.documentChanged(LexerEditorHighlighter.java:329)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:873)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:778)
	at com.intellij.openapi.editor.impl.DocumentImpl.deleteString(DocumentImpl.java:558)
	at com.intellij.openapi.editor.actions.BackspaceAction.a(BackspaceAction.java:66)
	at com.intellij.openapi.editor.actions.BackspaceAction.access$100(BackspaceAction.java:16)
	at com.intellij.openapi.editor.actions.BackspaceAction$Handler.executeWriteAction(BackspaceAction.java:35)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:51)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1028)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:210)
	at com.intellij.codeInsight.editorActions.BackspaceHandler.handleBackspace(BackspaceHandler.java:94)
	at com.intellij.codeInsight.editorActions.BackspaceHandler.executeWriteAction(BackspaceHandler.java:50)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:51)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1028)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$null$2(EditorActionHandler.java:202)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:110)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$3(EditorActionHandler.java:201)
	at com.intellij.openapi.editor.impl.CaretModelImpl.a(CaretModelImpl.java:363)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:452)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:355)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:346)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:201)
	at com.intellij.openapi.editor.actions.DeleteSelectionHandler.executeWriteAction(DeleteSelectionHandler.java:46)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:51)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1028)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:207)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:110)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:206)
	at com.intellij.codeInsight.lookup.impl.BackspaceHandler.doExecute(BackspaceHandler.java:39)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:207)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:110)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:96)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:139)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:97)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:105)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:80)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:668)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.b(IdeKeyEventDispatcher.java:520)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.b(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IndexOutOfBoundsException: Wrong offset: 304. Should be in range: [0, 303]
	at com.intellij.openapi.editor.ex.util.SegmentArray.offsetOutOfRange(SegmentArray.java:92)
	at com.intellij.openapi.editor.ex.util.SegmentArray.findSegmentIndex(SegmentArray.java:106)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.documentChanged(LexerEditorHighlighter.java:174)
	... 56 more
2018-08-02 22:08:16,947 [  85774]  ERROR - enapi.editor.impl.DocumentImpl - PyCharm 2018.2  Build #PY-182.3684.100 
2018-08-02 22:08:16,947 [  85774]  ERROR - enapi.editor.impl.DocumentImpl - JDK: 1.8.0_152-release 
2018-08-02 22:08:16,947 [  85774]  ERROR - enapi.editor.impl.DocumentImpl - VM: OpenJDK 64-Bit Server VM 
2018-08-02 22:08:16,947 [  85774]  ERROR - enapi.editor.impl.DocumentImpl - Vendor: JetBrains s.r.o 
2018-08-02 22:08:16,947 [  85774]  ERROR - enapi.editor.impl.DocumentImpl - OS: Linux 
2018-08-02 22:08:16,947 [  85774]  ERROR - enapi.editor.impl.DocumentImpl - Last Action: EditorBackSpace 
2018-08-02 22:08:16,947 [  85774]  ERROR - enapi.editor.impl.DocumentImpl - Current Command: Backspace 
```

**Comment by syuchan1005** [comment]
Could you show me your .gitprefix?

**Comment by gollum23** [comment]
Sure.
![screenshot_20180803_060921](https://user-images.githubusercontent.com/1058783/43640011-c416fb9c-96e3-11e8-889f-9e49ef397193.png)

**Comment by syuchan1005** [comment]
I feel that there is nothing wrong with it.
Are you using version 1.5.4?

**Comment by gollum23** [comment]
Yes, i update the extensión yesterday

![screenshot_20180803_090513](https://user-images.githubusercontent.com/1058783/43647125-55e0392c-96fc-11e8-93ce-9b8c78d1dd8a.png)

i can't see either emojis in commit window

![screenshot_20180803_090803](https://user-images.githubusercontent.com/1058783/43647267-baccdb88-96fc-11e8-9434-43f1ee723085.png)

Previous version 1.5.3.2 worked fine

**Comment by syuchan1005** [comment]
Sorry for the reply late

I released version 1.5.4.1, did you see the icon?

**Comment by gollum23** [comment]
hi, i updated yesterday but i still without see the icons both in gitprefix file and window commit

**Comment by syuchan1005** [comment]
Do you have any exception?

**Comment by gollum23** [comment]
No, i can't see any exception in idea.log file

**Comment by syuchan1005** [comment]
I tried it with Ubuntu on the virtual machine, but I could see the icon. The icon may not be loaded correctly. Can not see even if I reinstall the plugin?

![IDEA on Ubuntu](https://user-images.githubusercontent.com/8733829/43834354-c1817f92-9b48-11e8-8206-c949804500d6.png)

**Comment by gollum23** [comment]
Hi, Just now i tried reinstall the plugin but i have the same result, i use darcula theme in pycharm

**Comment by syuchan1005** [comment]
I could not see icon even with my Pycharm.　I will fix the issue.

**Comment by gollum23** [comment]
Thank you very much, the last update solve all issues both .gitprefix file and window commit
