### ISSUE TITLE
Can't commit

### ISSUE THREAD

**Issue by gollum23** [syuchan1005/GitPrefix#14]
Hi, just now i updated plugin to last version but i cant commit, when i try commit launch error. Attach error stack trace.
```
2018-08-13 11:00:45,119 [1765939]  ERROR - llij.ide.plugins.PluginManager - PyCharm 2018.2.1  Build #PY-182.3911.33 
2018-08-13 11:00:45,119 [1765939]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_152-release 
2018-08-13 11:00:45,119 [1765939]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2018-08-13 11:00:45,119 [1765939]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2018-08-13 11:00:45,119 [1765939]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2018-08-13 11:00:45,119 [1765939]  ERROR - llij.ide.plugins.PluginManager - Last Action: CheckinProject 
2018-08-13 11:00:46,166 [1766986]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 13/08/18 10:28 AM) 
2018-08-13 11:01:18,693 [1799513]  ERROR - llij.ide.plugins.PluginManager - Could not initialize class com.github.syuchan1005.gitprefix.PrefixUtil 
java.lang.NoClassDefFoundError: Could not initialize class com.github.syuchan1005.gitprefix.PrefixUtil
	at com.github.syuchan1005.gitprefix.PrefixPanel.createPrefixButton(PrefixPanel.java:61)
	at com.github.syuchan1005.gitprefix.PrefixPanel.<init>(PrefixPanel.java:45)
	at com.github.syuchan1005.gitprefix.commit.PrefixCheckinHandler.<init>(PrefixCheckinHandler.java:25)
	at com.github.syuchan1005.gitprefix.commit.PrefixCheckinHandlerFactory.createVcsHandler(PrefixCheckinHandlerFactory.java:17)
	at com.intellij.openapi.vcs.checkin.VcsCheckinHandlerFactory.createHandler(VcsCheckinHandlerFactory.java:38)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.createCheckinHandlers(CommitChangeListDialog.java:459)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.<init>(CommitChangeListDialog.java:294)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.commitChanges(CommitChangeListDialog.java:230)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.commitChanges(CommitChangeListDialog.java:154)
	at com.intellij.openapi.vcs.actions.AbstractCommonCheckinAction.performCheckIn(AbstractCommonCheckinAction.java:87)
	at com.intellij.openapi.vcs.actions.AbstractCommonCheckinAction.a(AbstractCommonCheckinAction.java:65)
	at com.intellij.openapi.vcs.changes.Waiter.onSuccess(Waiter.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.b(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:318)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:303)
	at com.intellij.openapi.vcs.changes.CallbackData.a(CallbackData.java:85)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue.invokeAfterUpdate(UpdateRequestsQueue.java:196)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.invokeAfterUpdate(ChangeListManagerImpl.java:410)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.invokeAfterUpdate(ChangeListManagerImpl.java:398)
	at com.intellij.openapi.vcs.actions.AbstractCommonCheckinAction.actionPerformed(AbstractCommonCheckinAction.java:65)
	at com.intellij.openapi.vcs.actions.AbstractVcsAction.actionPerformed(AbstractVcsAction.java:48)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:668)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:520)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.g(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-08-13 11:01:18,693 [1799513]  ERROR - llij.ide.plugins.PluginManager - PyCharm 2018.2.1  Build #PY-182.3911.33 
2018-08-13 11:01:18,693 [1799513]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_152-release 
2018-08-13 11:01:18,693 [1799513]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2018-08-13 11:01:18,693 [1799513]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2018-08-13 11:01:18,693 [1799513]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2018-08-13 11:01:18,693 [1799513]  ERROR - llij.ide.plugins.PluginManager - Last Action: CheckinProject 
```

**Comment by gollum23** [comment]
Solved with last update 1.5.4.4
