### ISSUE TITLE
Hope it can support 2019.3 version

### ISSUE THREAD

**Issue by agileago** [syuchan1005/GitPrefix#19]
thanks for your work

**Comment by syuchan1005** [comment]
I tried the plugin on IntelliJ IDEA Ultimate 2019.3 RC and it worked fine.
If it doesn't work, please let me know the problem in detail.

Thanks.

**Comment by agileago** [comment]
my fault(webstorm open a error plugin dialog when i upgrade). it support 2019.3

**Comment by agileago** [comment]
it seems has trouble.
![image](https://user-images.githubusercontent.com/11799110/70110415-d9491f00-1689-11ea-8c01-0fc5f91c89b4.png)
but it can work

**Comment by agileago** [comment]
error log

com.intellij.diagnostic.PluginException: Incorrect name specified in <fileType>, should be GitPrefix Resource, actual PrefixResource file [Plugin: com.github.syuchan1005.emojiprefix]
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiateFileTypeBean(FileTypeManagerImpl.java:491)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiatePendingFileTypes(FileTypeManagerImpl.java:464)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initializeComponent(FileTypeManagerImpl.java:666)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:97)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:49)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.kt:258)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:56)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl$preloadServices$future$1.run(PlatformComponentManagerImpl.kt:622)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:193)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by syuchan1005** [comment]
Thank you for your report.

This issue will be addressed in a future version (v 2.1.1).
Please wait for Jetbrains to approve the application.

**Comment by agileago** [comment]
ok. thanks for your work
