### ISSUE TITLE
Incompatible with Webstorm 2020.3

### ISSUE THREAD

**Issue by gollum23** [syuchan1005/GitPrefix#30]
**Describe the bug**
When I select a option from dropdown this not change the commit message neither maintain the selected item in dropdown

**StackTrace**
```text
Cannot create listener

com.intellij.diagnostic.PluginException: Cannot create listener com.github.syuchan1005.gitprefix.git.injector.GitInjectorManager [Plugin: com.github.syuchan1005.emojiprefix]
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:788)
	at com.intellij.util.messages.impl.CompositeMessageBus.subscribeLazyListeners(CompositeMessageBus.java:187)
	at com.intellij.util.messages.impl.CompositeMessageBus.doComputeSubscribers(CompositeMessageBus.java:157)
	at com.intellij.util.messages.impl.MessageBusImpl.computeSubscribers(MessageBusImpl.java:360)
	at com.intellij.util.messages.impl.CompositeMessageBus.computeSubscribers(CompositeMessageBus.java:151)
	at com.intellij.util.messages.impl.CompositeMessageBus$ToDirectChildrenMessagePublisher.lambda$publish$0(CompositeMessageBus.java:111)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.util.messages.impl.CompositeMessageBus$ToDirectChildrenMessagePublisher.publish(CompositeMessageBus.java:111)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:185)
	at com.sun.proxy.$Proxy35.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:104)
	at com.intellij.idea.ApplicationLoader$startApp$8.run(ApplicationLoader.kt:239)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: javassist/ClassPath
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:785)
	... 23 more
Caused by: java.lang.ClassNotFoundException: javassist.ClassPath PluginClassLoader[PluginDescriptor(name=GitPrefix, id=com.github.syuchan1005.emojiprefix, path=/home/gollum23/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/203.5981.135.plugins/GitPrefix.jar, version=2.1.4)] com.intellij.ide.plugins.cl.PluginClassLoader@74f799fc
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:129)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 26 more
```

**Screenshots**
Selecting option
![Screenshot_20201203_082350](https://user-images.githubusercontent.com/1058783/101023560-ef114e80-3540-11eb-961d-d3537dca1491.png)

After select an option
![Screenshot_20201203_082447](https://user-images.githubusercontent.com/1058783/101023667-1700b200-3541-11eb-8873-60b0ad65bec3.png)

Pycharm report about error
![Screenshot_20201202_105832](https://user-images.githubusercontent.com/1058783/100897093-566dc680-348d-11eb-8709-90bdb3881303.png)

**Desktop**
- IDE: Pycharm 2020.3 Build #PY-203.5981.165 (Also try with Webstorm)
- JRE: Java 11.0.9+11-b1145.21 amd64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- Platform: Manjaro Linux (KDE)

**.gitprefix file**
```text
:wrench:                Update
:bug:                   Bug Fixing
:horse_racing:          Performance
:construction:          WIP
:warning:               Migration
:lock:                  Security Fix
:recycle:               Refactoring
:art:                   Cosmetic
:books:                 Documentation
:no_entry:              Deletion
:white_check_mark:      Addition
:globe_with_meridians:  Translations
:sparkles:              New Feature
:police_car:            Test
:rocket:                Feature
:arrow_double_up:       Upgrade

```

**Comment by syuchan1005** [comment]
I released v2.1.12. It fixes above issue.
